name: 🐛 Bug
description: Report an issue to help improve the project.
title: "[BUG] <description>"
labels: ["bug", "status: awaiting triage"]
body:
  - type: checkboxes
    id: duplicates
    attributes:
      label: Verify this issue hasn't been reported before
      options:
        - label: I have checked "open" AND "closed" issues and this is not a duplicate
          required: true
  - type: textarea
    id: description
    attributes:
      label: What
      description: A clear description of the bug you have found.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide a brief list of steps to reproduce the bug.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable.
    validations:
      required: false
  - type: dropdown
    id: assignee
    attributes:
      label: Do you want to work on this issue?
      multiple: false
      options:
        - "No"
        - "Yes"
      default: 0
    validations:
      required: false
